# For local testing of the NetlifyCMS admin interface:
local_backend: true
# 1. on a terminal, run the "start NetlifyCMS proxy" script or "npx netlify-cms-proxy-server"
# 2. on a separate terminal, run "gatsby develop"

backend:
  name: github
  repo: Kevwy/museum-interactives-demo
  branch: main
  site_domain: am-interactives.netlify.app
  use_graphql: true

publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads
show_preview_links: true
display_url: https://am-interactives.netlify.app

slug:
  sanitize_replacement: "_"

collections:
  - name: "exhibits"
    label: "Exhibits"
    label_singular: "Exhibit"
    folder: "content/exhibit"
    create: true
    extension : "json"
    identifier_field: "name"
    summary: '{{fields.Title}}'
    slug: "{{slug}}"

    fields:
      - {label: "Unique identifier name", name: "name", widget: "string"}

      - label: "Title"
        name: "title"
        widget: "object"
        summary: '{{fields.en}}'
        fields:
          - {label: "Title (English)", name: "en", widget: "string"}
          - {label: "Title (Te Reo)", name: "reo", widget: "string", required: false}

      - label: "Description"
        name: "description"
        widget: "object"
        summary: '{{fields.en}}'
        fields:
          - {label: "Description (English)", name: "en", widget: "string"}
          - {label: "Description (Te Reo)", name: "reo", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image"}

      - label: "Hotspots"
        name: "hotspots"
        widget: "list"
        summary: '"{{id}}": {{fields.title}}'
        hint: >
          The "name" property of an image map and its corresponding hotspot's "unique identifier name" must be the identical. Multiple maps can refer to the same hotspot id.
        fields:
          - label: "Unique identifier name"
            name: "name"
            widget: "string"
            hint: 'Unique name used for hotspot mapping logic'

          - label: "Title"
            name: "title"
            widget: "object"
            summary: '{{fields.en}}'
            fields:
              - {label: "Title (English)", name: "en", widget: "string"}
              - {label: "Title (Te Reo)", name: "reo", widget: "string", required: false}

          - label: "Description"
            name: "description"
            widget: "object"
            summary: '{{fields.en}}'
            fields:
              - {label: "Description (English)", name: "en", widget: "text"}
              - {label: "Description (Te Reo)", name: "reo", widget: "text", required: false}

          - {label: "Image", name: "image", widget: "image"}

      - label: "JSON image hotspot mapping"
        name: "imageMap"
        widget: "code"
        default_language: "json"
        hint: >
          [{"name": string, "id": string, "shape": ["circle", "rect", "poly"], "coords": [number]}]

    # Under development: Custom NetlifyCMS widget integration
    #
    #  - label: "Image Map",
    #    name: "map",
    #    widget: "list"
    #    fields:
    #      - {label: "Hotspot name", name: "name", widget: "string"}
    #      - {label: "Hotspot ID", name: "id", widget: "string"}
    #      - {label: "Shape", name: "shape", widget: "string"}
    #      - label: "Coordinates"
    #        name: "coords"
    #        widget: "list"
    #        collapsed: true